---
- name: postgresql
  hosts: 127.0.0.1
  connection: local

  vars:
    ansible_become_pass: "lucifer317"

  tasks:
    - name: Install pip and Docker Python library
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python-pip
          - docker

