---
- name: postgresql
  hosts: 127.0.0.1
  connection: local

  vars:
    ansible_become_pass: "lucifer317"

  tasks:
    - name: Install pip and docker.io
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python-pip
          - docker.io

    - name: Install Docker Python library
      become: yes
      pip: 
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker

    - name: Build Docker images from Dockerfiles
      docker_image:
        name: "{{ item.name }}"
        tag: "{{ item.tag }}"
        path: "./{{ item.directory }}"
        state: build
      with_items:
        - { name: postgres, tag: "postgres", directory: postgres }

    - name: Run a postgres container
      docker_container:
        image: postgres:postgres
        name: postgres
        state: started
        volumes_from: data
        ports: "5432:5432"
        env:
          POSTGRES_USER: "yungshun"
          POSTGRES_PASSWORD: "lucifer317" 
          PGDATA: "/var/lib/postgresql/data" 
